# Generated by Django 2.2.2 on 2019-06-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0004_auto_20190612_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='by_first_player',
        ),
    ]
