# Generated by Django 2.2.2 on 2019-06-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0005_remove_move_by_first_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='by_first_player',
            field=models.BooleanField(default=True, editable=False),
            preserve_default=False,
        ),
    ]
